Sign in/Sign up -> normally + google and facebook login

User Interface:-
View Books 
Indivisual pages for books




Future additions:
1. Cart for user
2. Reading availability for books using apis 


